apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
        - name: go-demo-app
          image: v101.158.177.255.242.nip.io:5443/go-demo-app:1.0.0
          env:
            - name: DATABASE_URL
              value: "go-demo-app-postgres:5432/docker"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: go-demo-app-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-demo-app-db-secret
                  key: password
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-demo-app
spec:
  type: NodePort
  selector:
    app: go-demo-app
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: go-demo-app-db-secret
data:
  username: ZG9ja2Vy
  password: cGFzc3cwcmQ=
